In [24]:
import numpy as np

In [25]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([0])


In [26]:
ar3 = np.append(arr1, arr2)
print(ar3)
ar4 = np.insert(arr1, 0, arr2)
print(ar4)

[1 2 3 4 5 0]
[0 1 2 3 4 5]


In [27]:

np_arr1 = np.array([[1, 2], [3, 4]])
np_arr2 = np.array([[10, 20], [30, 40]])
np.append(np_arr1, np_arr2)
print(np.append(np_arr1, np_arr2))

np.append(np_arr1, np_arr2, axis=0)

[ 1  2  3  4 10 20 30 40]


array([[ 1,  2],
       [ 3,  4],
       [10, 20],
       [30, 40]])

In [28]:
np.append(np_arr1, np_arr2, axis=1)

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [29]:
npZeros22 = np.zeros((2, 2))
print(npZeros22)
npZeros0 = np.zeros((1))
print(npZeros0)



[[0. 0.]
 [0. 0.]]
[0.]
