In [ ]:
import numpy as np

In [ ]:
# 1
my100Primes = np.array([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97])
my100PrimesLength = len(my100Primes)

In [ ]:
#  Make into a function 

def prime_array(primeList):
    index = 1
    for value in primeList:
        print(index, value)
        index += 1      

In [ ]:
# 2
def orderedPrimes(my100Primes):
    # orderedPrimes = []
    index = 1
    for value in my100Primes:
        print(index, value)
        index += 1
        result = np.array(my100Primes) 

In [ ]:
# 3
orderedPrimesArray = np.array(orderedPrimes(my100Primes))

In [40]:
orderedPrimesArray.shape
orderedPrimesArray.ndim
print(orderedPrimesArray.shape)  # result: ()
print(orderedPrimesArray.ndim)   # result:  0

()
0


In [48]:
testarr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = testarr.reshape(4, 3)

print(testarr   )
print(testarr.shape)
print(testarr.ndim)
print("Now for newarr")
print(newarr.shape)
print(newarr.ndim)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1
Now for newarr
(4, 3)
2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# orderedPrimesArray 

